rootProject.name = extra["project.name"]!!.toString()

include(":flexbans-api")
include(":flexbans-core")
include(":flexbans-bukkit")
include(":flexbans-bungee")
include(":flexbans-velocity")
include(":flexbans-bundle")

project(":flexbans-api").projectDir = file("flexbans-api")
project(":flexbans-core").projectDir = file("flexbans-core")
project(":flexbans-bukkit").projectDir = file("flexbans-bukkit")
project(":flexbans-bungee").projectDir = file("flexbans-bungee")
project(":flexbans-velocity").projectDir = file("flexbans-velocity")
project(":flexbans-bundle").projectDir = file("flexbans-bundle")
