/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "FlexBans"
include(":FlexBansAPI")
include(":FlexBansCore")
include(":FlexBansPlatforms")
project(":FlexBansAPI").projectDir = file("api")
project(":FlexBansCore").projectDir = file("core")
project(":FlexBansPlatforms").projectDir = file("platforms")
