/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
    id("com.gradleup.shadow") version "9.2.2"
}

repositories {
    mavenCentral()
    maven {
        name = "papermc-repo"
        url = uri("https://repo.papermc.io/repository/maven-public/")
    }
    maven {
        name = "sonatype"
        url = uri("https://oss.sonatype.org/content/repositories/snapshots/")
    }
    maven {
        name = "jitpack"
        url = uri("https://jitpack.io")
    }
}

dependencies {
    api(project(":FlexBansCore"))
    api(project(":FlexBansAPI"))

    compileOnly("com.velocitypowered:velocity-api:3.3.0-SNAPSHOT")
    compileOnly("net.md-5:bungeecord-api:1.21-R0.1-SNAPSHOT")
    compileOnly("io.papermc.paper:paper-api:1.21.10-R0.1-SNAPSHOT")
    compileOnly("com.gitlab.ruany:LiteBansAPI:0.5.0")
}

tasks.withType<Jar> {
    manifest {
        attributes["Main-Class"] = "fr.neocle.flexbans.GuiLauncher"
    }
}

val moveJar by tasks.registering {
    dependsOn(tasks.named("shadowJar"))
    doLast {
        val shadowJarTask = tasks.named("shadowJar").get() as Jar
        val jarFile = shadowJarTask.archiveFile.get().asFile
        val targetDir = file("../build/libs/")
        val targetFile = File(targetDir, "FlexBans-1.0.0-SNAPSHOT.jar")

        targetDir.mkdirs()
        jarFile.copyTo(targetFile, overwrite = true)
        jarFile.delete()
    }
}

tasks.named("build") {
    finalizedBy(moveJar)
}

description = "FlexBansPlatforms"
