/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
    id("com.gradleup.shadow") version "9.2.2"
}

dependencies {
    api(project(":FlexBansCore"))
    api(project(":FlexBansAPI"))
    compileOnly(libs.com.velocitypowered.velocity.api)
    compileOnly(libs.net.md.v5.bungeecord.api)
    compileOnly(libs.io.papermc.paper.paper.api)
    compileOnly(libs.com.gitlab.ruany.litebansapi)
}

tasks.withType<Jar> {
    manifest {
        attributes["Main-Class"] = "fr.neocle.flexbans.GuiLauncher"
    }
}

val moveJar by tasks.registering {
    dependsOn(tasks.named("shadowJar"))
    doLast {
        val shadowJarTask = tasks.named("shadowJar").get() as Jar
        val jarFile = shadowJarTask.archiveFile.get().asFile
        val targetDir = file("../build/libs/")
        val targetFile = File(targetDir, "FlexBans-1.0.0-SNAPSHOT.jar")

        targetDir.mkdirs()
        jarFile.copyTo(targetFile, overwrite = true)
        jarFile.delete()
    }
}

tasks.named("build") {
    finalizedBy(moveJar)
}

description = "FlexBansPlatforms"
