/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":FlexBansAPI"))
    api(libs.org.eclipse.jetty.jetty.server)
    api(libs.org.mindrot.jbcrypt)
    api(libs.com.h2database.h2)
    api(libs.org.yaml.snakeyaml)
    api(libs.org.snakeyaml.snakeyaml.engine)
    api(libs.net.kyori.adventure.api)
    api(libs.net.kyori.adventure.platform.bungeecord)
    api(libs.net.kyori.adventure.text.minimessage)
    compileOnly(libs.net.md.v5.bungeecord.api)
    compileOnly(libs.io.papermc.paper.paper.api)
    compileOnly(libs.com.velocitypowered.velocity.api)
    compileOnly(libs.javax.servlet.javax.servlet.api)
    compileOnly(libs.org.xerial.sqlite.jdbc)
    compileOnly(libs.mysql.mysql.connector.java)
    compileOnly(libs.org.geysermc.geyser.api)
    compileOnly(libs.org.geysermc.floodgate.api)
    compileOnly(libs.com.gitlab.ruany.litebansapi)
    implementation("com.google.code.gson:gson:2.11.0")
}

description = "FlexBansCore"
