name: FlexBans
api: 1.0.0
api-version: 1.13
main: fr.neocle.flexbans.bukkit.FlexBansBukkit
version: 1.0-SNAPSHOT
author: Neocle

commands:
  flexbans:
    description: Main command for FlexBans plugin.
    usage: "/flexbans <subcommand>"
    aliases: [ lw, lbw ]
    permission: flexbans.use
    permission-message: You do not have permission to execute this command.

permissions:
  flexbans.use:
    description: Allows access to the FlexBans commands.
    default: true

  flexbans.reload:
    description: Allows reloading the FlexBans configuration.
    default: op

  flexbans.verify:
    description: Allows users to verify their access to the dashboard.
    default: true

folia-supported: true