/*
 * This file was generated by the Gradle 'init' task.
 */
plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.org.yaml.snakeyaml)
    api(libs.org.snakeyaml.snakeyaml.engine)
    compileOnly(libs.com.velocitypowered.velocity.api)
    compileOnly(libs.net.md.v5.bungeecord.api)
    compileOnly(libs.io.papermc.paper.paper.api)
}

description = "FlexBansAPI"
